kind: ZarfPackageConfig
metadata:
  name: k8s-manifests
  description: |
    A Zarf package that deploys kubernetes manifests
  version: 0.0.1
components:
  - name: k8s-folder
    description: Does a kubectl create -f on the k8s folder
    # prompt the user to create package?
    required: true
    # new
    manifests:
      - name: k8s-folder
        namespace: webserver
        # webserver deployment, svc
        files:
          - zarf-practice.yaml
    # required to tell zarf where your image lives
    images:
      - docker.io/cmwylie19/hello-zarf
