kind: ZarfPackageConfig
metadata:
  name: k8s-manifests
  description: |
    A Zarf package that deploys kubernetes manifests
  version: 0.0.1
components:
  - name: k8s-folder
    description: Does a kubectl create -f on the k8s folder
    required: true
    manifests:
      - name: k8s-folder
        namespace: webserver
        files:
          - zarf-practice.yaml
    images:
      - docker.io/cmwylie19/hello-zarf
